import { genericConfirm } from "../../cli/readUser";
import type { Project } from "../../types/projects";
import { getProjectById } from "../readers/finder";
import { homedir } from "os";
import pc from "picocolors";

const PDFDocument = require("pdfkit");
const fs = require("fs");

export const generatePDF = async (id: number, path: string) => {
  const doc = new PDFDocument();

  const isExist = Bun.file(path);
  let userReq = null;
  if (await isExist.exists()) {
    userReq = await genericConfirm(
      `File ${path} already exists. Overwrite?`,
      false,
    );
    if (!userReq) {
      console.warn(pc.red("Operation canceled."));
      process.exit(0);
    }
  }

  // Informações do Projeto e cliente
  const projectData: Project | null | undefined = await getProjectById(id);
  if (!projectData) {
    console.error("Project not found");
    process.exit(1);
  }

  // Informações do freelancer
  const configPath = `${homedir()}/.invoicerc`;
  const file = Bun.file(configPath);
  if (!(await file.exists())) {
    console.error(
      "ERROR: Still don't have a configuration file, generate one using the `setup` command",
    );
    process.exit(1);
  }

  let freelancerData = null;

  try {
    freelancerData = await file.json();
  } catch (error) {
    console.error(
      "ERROR: The configuration file syntax is corrupt, use the `setup` command to generate a valid configuration",
    );
    process.exit(1);
  }

  const { name, email } = freelancerData;
  if (!name || !email) {
    console.error(
      "ERROR: The configuration file is invalid, generate a valid one using the `setup` command",
    );
    process.exit(1);
  }

  // Geração do PDF
  doc.pipe(fs.createWriteStream(path));
  // HEADER
  doc
    .font("Helvetica-Bold")
    .fontSize(20)
    .text(`INVOICE #${projectData.id}`, 50, 50);
  doc
    .font("Helvetica")
    .fontSize(10)
    .text(new Date().toLocaleDateString(), 450, 50);

  doc
    .font("Helvetica")
    .fontSize(10)
    .text(freelancerData.name, 50, 80)
    .text(freelancerData.email, 50, 95);

  // BILL TO
  doc.font("Helvetica-Bold").fontSize(12).text("BILL TO:", 50, 130);
  doc
    .font("Helvetica")
    .fontSize(10)
    .text(projectData.clientName, 50, 150)
    .text(projectData.clientEmail, 50, 165)
    .text(projectData.clientCompany, 50, 180);

  // PROJECT DETAILS
  doc.font("Helvetica-Bold").fontSize(12).text("PROJECT DETAILS:", 50, 220);
  doc
    .font("Helvetica")
    .fontSize(10)
    .text(`Project: ${projectData.name}`, 50, 240)
    .text(`Description: ${projectData.description}`, 50, 255)
    .text(
      `Type: ${projectData.chargeType === "fixed" ? "Fixed Price" : "Hourly Rate"}`,
      50,
      270,
    )
    .text(
      `Period: ${projectData.startDate} to ${projectData.deliveryForecast}`,
      50,
      285,
    );

  // PAYMENT
  doc.font("Helvetica-Bold").fontSize(12).text("PAYMENT DETAILS:", 50, 320);
  const remaining = projectData.contactBudget! - projectData.initialPay!;
  doc
    .font("Helvetica")
    .fontSize(10)
    .text(
      `Contract Value: R$ ${projectData.contactBudget!.toFixed(2)}`,
      50,
      340,
    )
    .text(
      `Initial Payment (paid): R$ ${projectData.initialPay!.toFixed(2)}`,
      50,
      355,
    )
    .font("Helvetica-Bold")
    .fontSize(14)
    .text(`AMOUNT DUE: R$ ${remaining.toFixed(2)}`, 50, 390)
    .font("Helvetica")
    .fontSize(10)
    .text(`Due Date: ${projectData.expectedPayDate}`, 50, 415);

  // FOOTER
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#999")
    .text("Generated by Invoice CLI", 50, 710);
  doc.end();
};
